config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users

  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_image
    if image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    else
      image
    end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment,presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, presence: true, length: { in: 2..20}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(resource)
  end

  def after_sign_out_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    if @comment.save
      redirect_to book_path(@book)
    else
      puts "投稿失敗"
      redirect_to book_path(@book)
    end
  end


  def destroy
    @book = Book.find(params[:book_id])
    @comment = BookComment.find(params[:id])
    @comment.destroy
    redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :move_to_signed_in  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all
    @comments = BookComment.all
    flash[:notice] = "You have created book successfully."
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @comment = BookComment.new
    @comments = BookComment.all
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  private
  
  def move_to_signed_in
    unless user_signed_in?
      redirect_to '/users/sign_in'
    end
  end
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_to request.referer
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :move_to_signed_in  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "Welcome! You have signed up successfully."
    else
      @books = Book.all
      render :index
    end
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def index
    @user = current_user
    @users = User.all
  end

private

  def move_to_signed_in
    unless user_signed_in?
      redirect_to '/users/sign_in'
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_image_helper.rb
module PostImageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_bookers.html.erb
<% if @book && @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<div class="row">
  <div class="col-md-8">
  <h2>User info</h2>
  <div class="row">
    <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
      <tbody>
        <tr>
      	  <th>name</th>
      	  <th><%= user.name %></th>
        </tr>
        <tr>
      	  <th>introduction</th>
      	  <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
  </div>

<div class="row">
  <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog" aria-hidden="true"></i>
  <% end %>
</div>
<%= form_with model: @book, url: books_path,  method: :post do |f| %>
  <h2 class="mt-3">New book</h2>
  <h4>Title</h4>
  <div class="form-group">
    <label for="book_title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
<% end %>
</div>
</div>

app/views/books/comment.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <% if flash[:notice].present? %>
          <%= flash[:notice] %>
      <% end %>
      <%= render 'bookers', book: @book_new, user: @user%>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <% if@book.errors.any? %>
                <%= @book.errors.count %>error prohibited this obj from being saved:
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
      <%= form_with model: @book, url: book_path(@book), method: :patch do |f| %>
      <h1>Editing Book</h1>
      <div class="form_group">
        <p>Title</p>
        <%= f.text_field :title %>
      </div>
     <div class="form_group">
      <p>Opinion</p>
      <%= f.text_area :body %>
      </div>
      <div class="form_group">
        <%= f.submit 'Update Book', class: "btn btn-success md-3" %>
      </div>

<% end %>
    </div>
    <%= link_to "Show",book_path %>|
    <%= link_to "Back",books_path %>
  </div>
</div>

app/views/books/index.html.erb
<main>
  <div class="container px px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'bookers', books: @book, user: @user %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
              <% @books.each do |book| %>
              <tr>
                  <%= link_to user_path(@user) do %>
                  <td>
                      <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(100,100) %>
                      <% end %>
                  </td>
                  <td>
                    <%= link_to book_path(book) do %>
                    <%= book.title %>
                    <% end %>
                  </td>
                  <% end %>
                  <td><p><%= book.body %></p></td>
                  <td>
                    <% if book.favorited_by?(current_user) %>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                      <span class="fa-solid fa-heart"></span><%= book.favorites.count %>いいね
                    <% end %>
                    <% else %>
                      <%= link_to book_favorites_path(book),method: :post do %>
                        <span class="fa-regular fa-heart"></span><%= book.favorites.count %>いいね
                    <% end %>
                    <% end %>
                  </td>
                  <td>
                    コメント数:<%= book.book_comments.count %>
                  </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
  </div>
</main>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <% if flash[:notice].present? %>
          <%= flash[:notice] %>
      <% end %>
      <%= render 'bookers', book: @book_new, user: @user%>
    </div>





  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
      <tbody>
          <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= image_tag @book.user.get_profile_image(100,100) %>
                  </br><%= @user.name %>
                <% end %>
              </td>

              <td>
                <%= link_to user_path(@user) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td><%= @book.body %></td>
                <% if current_user == @user  %>
                  <td><a class="btn btn-sm btn-success" href="<%= edit_book_path(@book) %>"><i class="edit"></i>Edit</a></td>
                  <td><a data-confirm="本当に消しますか？"class="btn btn-sm btn-danger" rel="nofollow" data-method="delete" href="<%= book_path(@book) %>">Destroy</a></td>
                <% else %>
                <% end %>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <span class="fa-solid fa-heart"></span><%= @book.favorites.count %>いいね
                  <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <span class="fa-regular fa-heart"></span><%= @book.favorites.count %>いいね
                  <% end %>
                <% end %>
              </td>
              <td>
                コメント数:<%= @book.book_comments.count %>
              </td>
          </tr>
      </tbody>
  </table>

<table class="table">
    <tbody>
      <% @book.book_comments.each do |comment| %>
        <tr>
          <td>
            <%= image_tag comment.user.get_profile_image(100,100) %>
          </td>
          <td>
            <%= comment.user.name %>
          </td>
          <td>
            <%= comment.comment %>
          </td>
          <td>
            <% if comment.user ==  current_user %>
              <%=  link_to "Destroy", book_book_comment_path(@book,comment), method: :delete, class:"btn btn-sb btn-danger"  %>
            <% else %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
    <%= form_with model: [@book, @comment], url: book_book_comments_path(@book) do |f| %>
                <%= f.text_area :comment, rows: '5' %>
                <%= f.submit "送信" %>
              <% end %>
  </div>
</diV>
</div>
</div>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">
            Welcome to
            <i class="fas fa-book" aria-hidden="true"></i>
            <strong>Bookers!</strong>
        </h1>
    </div>
</div>

app/views/homes/top.html.erb
            <main>
                <p id="notice"></p>
                <div class="container">
                    <div class="row">
                        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                            <% if flash[:notice].present? %>
                                <%= flash[:notice] %>
                            <% end %>
                            <h1>welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong> !!
                            </h1>
                            <p>In <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>, </p>
                            <p>you can share and exchange your opinions , inpressions , and emotions</p>
                            <p> about various books!</p>
                            <div class="btn-wrapper col-10 mx-auto">
                                <div class="row">
                                    <a class="btn btn-info btn-sm btn-block mb-3" href="<%= new_user_session_path %>">Log in</a>
                                </div>
                                <div class="row">
                                    <a class="btn btn-success btn-sm btn-block sign_up" href="<%= new_user_registration_path %>">Sign up</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1fb06ac57c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="<%= root_path %>"><span>Bookers</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <% if user_signed_in? %>
                          <li>
                              <%= link_to user_path(current_user), class:"nav-link text-light" do %>
                                  <i class="fas fa-home" aria-hidden="true"></i> Home
                              <% end %>
                          </li>
                        <% else %>
                          <li>
                            <%= link_to root_path, class:"nav-link text-light" do %>
                              <i class="fas fa-home" aria-hidden="true"></i> Home
                            <% end %>
                          </li>
                        <% end %>
                        <% if user_signed_in? %>
                          <li>
                              <%= link_to users_path, class:"nav-link text-light" do %>
                                  <i class="fas fa-users" aria-hidden="true"></i> Users
                              <% end %>
                          </li>
                        <% else %>
                          <li>
                            <%= link_to about_path, class:"nav-link text-light" do %>
                              <i class="fas fa-link" aria-hidden="true"></i> About
                            <% end %>
                          </li>
                        <% end %>

                        <% if user_signed_in? %>
                          <li>
                            <%= link_to books_path, class:"nav-link text-light" do %>
                              <i class="fas fa-book-open" aria-hidden="true"></i> Books
                            <% end %>
                          </li>
                        <% else %>
                          <li>
                            <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                              <i class="fas fa-user-plus" aria-hidden="true"></i> Sign up
                            <% end %>
                          </li>
                        <% end %>

                        <% if user_signed_in? %>
                          <li>
                              <%= link_to destroy_user_session_path, class:"nav-link text-light", data: { method: :delete } do %>
                                  <i class="fas fa-sign-out-alt" aria-hidden="true"></i> Log out
                              <% end %>
                          </li>
                        <% else %>
                          <li>
                            <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                              <i class="fas fa-sign-in-alt" aria-hidden="true"></i> Log in
                            <% end %>
                          </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
            </div>
            </div>
            </navbar>
          </header>
    <%= yield %>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <% if@user.errors.any? %>
                <%= @user.errors.count %>error prohibited this obj from being saved:
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
            <h2>User info</h2>
            <%= form_with model: @user do |f| %>
                <div class="form_group">
                    <p><%= f.label :name %></p>
                    <p><%= f.text_field :name, autofocus: true, id:"inputName" %></p>
                </div>
                <div class="form_group">
                    <p><%= f.label :Image %></p>
                    <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>
                </div>
                <div class="form_group">
                    <p><%= f.label :InputIntroduction %></p>
                    <p><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %></p>
                </div>
                <div class="actions">
                    <p><%= f.submit 'Update User', class: "btn btn-secondary md-3" %></p>
                </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<main>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
                <%= render 'books/bookers', book: @book ,user: @user%>
            </div>
            
            <div class="col-md-8 offset-md-1">
                <h2>Users</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>image</th>
                            <th>name</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
    
                    <tbody>
                        <% @users.each do |user| %>
                        <tr>
                            <td><%= image_tag user.get_profile_image(100,100) %></td>
                            <td><%= user.name %></td>
                            <td>
                                <%= link_to "Show",user_path(user) %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <% if flash[:notice].present? %>
          <%= flash[:notice] %>
      <% end %>
      <%= render 'books/bookers', book: @book ,user: @user%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <tbody>
            <tr>
              <% @books.each do |book| %>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <p><%= image_tag book.user.get_profile_image(100,100) %></p>
              </td>
              <% end %>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                  <span class="fa-solid fa-heart"></span><%= book.favorites.count %>いいね
                <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book),method: :post do %>
                  <span class="fa-regular fa-heart"></span><%= book.favorites.count %>いいね
                <% end %>
                <% end %>
              </td>
              <td>
                  コメント数:<%= book.book_comments.count %>
              </td>
            </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>